[package]
name = "finfmt"
version = "0.2.0"
edition = "2024"
description = "Zero-allocation financial message encoding and decoding library"
readme = "README.md"
license = "MIT"
repository = "https://github.com/nakedible/finfmt-rs"
rust-version = "1.92"
keywords = ["iso8583", "apacs", "financial", "ebcdic", "encoding"]
categories = ["encoding", "parser-implementations"]
include = [
    "/Cargo.toml",
    "/CHANGELOG.md",
    "/LICENSE",
    "/README.md",
    "/src/**",
    "/examples/**",
    "/benches/**",
]

[features]
default = ["serde"]
asm-inspect = []
compact_str = ["dep:compact_str"]
no-panic = ["dep:no-panic"]
serde = ["dep:serde"]

[dependencies]
compact_str = { version = "0.10.0", optional = true }
no-panic = { version = "0.1.37", optional = true }
serde = { version = "1.0.229", features = ["derive"], optional = true }

[dev-dependencies]
compact_str = { version = "0.10.0", features = ["serde"] }
proptest = "1.11.0"
serde_json = "1.0.151"
zenbench = "0.1.9"

[[bench]]
name = "bytes"
harness = false
required-features = ["asm-inspect"]

[[bench]]
name = "decimal"
harness = false
required-features = ["asm-inspect"]

[[bench]]
name = "codepage"
harness = false
required-features = ["asm-inspect"]

[[bench]]
name = "int"
harness = false
required-features = ["asm-inspect"]

[[bench]]
name = "nibble"
harness = false
required-features = ["asm-inspect"]

[[bench]]
name = "text"
harness = false
required-features = ["asm-inspect"]

[[bench]]
name = "bertlv"
harness = false
required-features = ["asm-inspect"]

[[bench]]
name = "bitmap"
harness = false
required-features = ["asm-inspect"]

[[bench]]
name = "validation"
harness = false
required-features = ["asm-inspect"]

[[bench]]
name = "message"
harness = false
required-features = ["compact_str", "serde"]

[[example]]
name = "nibss"
required-features = ["compact_str", "serde"]
test = true

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1
