#![forbid(unsafe_code)]

#[cfg(feature = "asm-inspect")]
pub mod asm;
pub mod bitmap;
pub mod composite;
pub mod extras;
pub mod field;
pub mod primitive;
mod scalarfmt;
mod types;
mod utils;

pub use bitmap::{Bitmap, BitmapFormat, BitmapLayout, decode_bitmap, encode_bitmap};
#[cfg(feature = "serde")]
pub use composite::SerdeScalar;
pub use composite::{
    AbsentBytes, AbsentFmt, BoundedList, ContextDecode, Empty, FieldDecode, FieldEncode, FixedAreaList, FixedBytes, FixedValue, Frame,
    NoPadding, NoTrailingFields, OptionAs, PaddingByte, ScalarDecode, ScalarEncode, Separator, TlvEntry, TlvExtras, TlvList, TlvPadding,
    TrailingField, TrailingLengthFrame, decode, encode,
};
pub use field::{
    Alpha, Alphanum, Ascii, AsciiLength, AsciiPrintable, Bcd, BcdBytes, Bcdz, BerLength, BerTag, Binary, BlankableEbcdicLength, Check,
    ConstBytes, Count, DecodeCheck, Ebcdic037, Ebcdic037Ascii, Ebcdic1142, Ebcdic1142Text, EbcdicLength, EbcdicPrintable, Field, Fill,
    Fixed, FixedBinaryBe, FixedComp3, FixedNibbleInt, FixedSignedBinaryBe, FixedSignedComp3, FixedSignedZonedEbcdic, Hex, HexEven,
    Identity, ImpliedDecimal, Iso88591, Length, LengthSpec, LowerHex, LowerHexEven, MinusPrefix, Numeric, Offset, PackNibbles,
    PackNibblesLeft, PackNibblesRight, PadLeft, PadLeftEven, PadRight, PadRightEven, Per, Rest, SignPrefix, Step, StrictBerTag, Track2,
    Truncate, UnpackNibbles, UpperAlpha, UpperAlphanum, UpperAsciiPrintable, UpperHex, UpperHexEven,
};
pub use scalarfmt::ScalarFmt;
pub use types::{CompositeError, Error, PathSegment};

#[doc(hidden)]
pub mod __private {
    use core::marker::PhantomData;

    use crate::{CompositeError, Error};

    /// A field the container may omit, seen as an `Option`: an `Option<T>`
    /// itself, or a `bool` flag, an optional constant that is either present
    /// or not.
    pub trait AsOption {
        type Inner;
        fn as_option(&self) -> Option<&Self::Inner>;
    }

    impl<T> AsOption for Option<T> {
        type Inner = T;
        #[inline(always)]
        fn as_option(&self) -> Option<&T> {
            self.as_ref()
        }
    }

    impl AsOption for bool {
        type Inner = ();
        #[inline(always)]
        fn as_option(&self) -> Option<&()> {
            if *self { Some(&()) } else { None }
        }
    }

    /// A field from its decoded local: itself, or a `bool` flag from an
    /// optional constant's `Option<()>`.
    pub trait FromLocal<L>: Sized {
        fn from_local(local: L) -> Self;
    }

    impl<T> FromLocal<T> for T {
        #[inline(always)]
        fn from_local(local: T) -> T {
            local
        }
    }

    impl FromLocal<Option<()>> for bool {
        #[inline(always)]
        fn from_local(local: Option<()>) -> bool {
            local.is_some()
        }
    }

    /// The constant bytes of a record's field at position `I`, generated by
    /// `wire_type!` on the record so no generated name can shadow a user path.
    pub trait FieldBytes<const I: usize> {
        const BYTES: &'static [u8];
    }

    /// [`FieldBytes`] as a [`crate::ConstBytes`] type.
    pub struct RecordBytes<R: ?Sized, const I: usize>(PhantomData<fn() -> *const R>);

    impl<R: FieldBytes<I> + ?Sized, const I: usize> crate::ConstBytes for RecordBytes<R, I> {
        const BYTES: &'static [u8] = R::BYTES;
    }

    /// The absent encoding of a record's field at position `I`.
    pub trait FieldAbsent<const I: usize> {
        fn encode_absent(output: &mut &mut [u8], scratch: &mut [u8]) -> Result<(), Error>;
    }

    /// [`FieldAbsent`] as an [`crate::AbsentFmt`] type.
    pub struct RecordAbsent<R: ?Sized, const I: usize>(PhantomData<fn() -> *const R>);

    impl<R: FieldAbsent<I> + ?Sized, const I: usize> crate::AbsentFmt for RecordAbsent<R, I> {
        #[inline(always)]
        fn encode_absent(output: &mut &mut [u8], scratch: &mut [u8]) -> Result<(), Error> {
            R::encode_absent(output, scratch)
        }
    }

    /// A byte pattern spelled as a byte string, an array, or a constant of
    /// type `[u8; N]`, `&[u8; N]` or `&[u8]`, as one `&'static [u8]`.
    pub struct BytePattern<T>(pub T);

    impl<const N: usize> BytePattern<[u8; N]> {
        pub const fn bytes(&'static self) -> &'static [u8] {
            &self.0
        }
    }

    impl<const N: usize> BytePattern<&'static [u8; N]> {
        pub const fn bytes(&self) -> &'static [u8] {
            self.0
        }
    }

    impl BytePattern<&'static [u8]> {
        pub const fn bytes(&self) -> &'static [u8] {
            self.0
        }
    }

    /// Infer a decoded binding's type from the record field it fills.
    #[inline(always)]
    pub fn same_type<R, T: ?Sized>(_value: &T, _field: fn(&R) -> &T) {}

    #[inline(always)]
    pub fn cold_path() {
        crate::utils::cold_path();
    }

    #[inline(always)]
    pub fn encode_variant<T: ?Sized, F: crate::composite::FieldEncode<T>>(
        output: &mut &mut [u8],
        scratch: &mut [u8],
        value: &T,
    ) -> Result<(), CompositeError> {
        crate::composite::encode_variant::<T, F>(output, scratch, value)
    }

    #[inline(always)]
    pub fn decode_variant<'a, T, E, F, W>(input: &mut &'a [u8], scratch: &mut &'a mut [u8], wrap: W) -> Result<E, CompositeError>
    where
        F: crate::composite::FieldDecode<'a, T>,
        W: FnOnce(T) -> E,
    {
        crate::composite::decode_variant::<T, E, F, W>(input, scratch, wrap)
    }
}
